# task config
task: heading_task

# simulation config
jsbsim_freq: 60
agent_interaction_steps: 12 # step 0.2s

# termination config
max_steps: 3000              # episode: 600s
altitude_limit: 2500
acceleration_limit_x: 2.0
acceleration_limit_y: 2.0
acceleration_limit_z: 2.0

# init config
init_config: {
  blue_fighter: {
    aircraft_name: f16,
    ic_h_sl_ft: 11000.0,
    ic_lat_geod_deg: 60.0,
    ic_long_gc_deg: 120.0,
    ic_psi_true_deg: 0.0,
    ic_u_fps: 800.0,
  }
}

# reward config
AltitudeReward_safe_altitude: 4.0
AltitudeReward_danger_altitude: 3.5
AltitudeReward_Kv: 0.2
AltitudeReward_render: false

SmoothActionReward_render: false
