max_episode_steps: 1500
reward_scale: 100.0
final_reward_scale: 50.0
danger_altitude: 3.5
safe_altitude: 4.0
target_dist: 3.0
KL: 1.0
Kv: 0.2
b_aircraft_name: f16
b_ic_h_sl_ft: 19685.03937007874
b_ic_lat_geod_deg: 60.0
b_ic_long_gc_deg: 120.0
b_ic_psi_true_deg: 0.0
b_ic_u_fps: 800.0
r_aircraft_name: f16
r_ic_h_sl_ft: 19685.03937007874
r_ic_lat_geod_deg: 60.05
r_ic_long_gc_deg: 120.0
r_ic_psi_true_deg: 0.0
r_ic_u_fps: 800.0
