# task config
task: selfplay_task

# simulation config
jsbsim_freq: 60
agent_interaction_steps: 12 # step 0.2s

# termination config
max_steps: 900              # episode: 180s
altitude_limit: 2500
acceleration_limit_x: 10.0
acceleration_limit_y: 10.0
acceleration_limit_z: 10.0

# init config
init_config: {
  blue_fighter: {
    aircraft_name: f16,
    ic_h_sl_ft: 19685.03937007874,
    ic_lat_geod_deg: 60.0,
    ic_long_gc_deg: 120.0,
    ic_psi_true_deg: 0.0,
    ic_u_fps: 800.0,
  },
  red_fighter: {
    aircraft_name: f16,
    ic_h_sl_ft: 19685.03937007874,
    ic_lat_geod_deg: 60.05,
    ic_long_gc_deg: 120.0,
    ic_psi_true_deg: 180.0,
    ic_u_fps: 800.0,
  }
}

# reward config
PostureReward_scale: 100.0
PostureReward_potential: true
PostureReward_render: false
target_dist: 3.0

AltitudeReward_render: false
safe_altitude: 4.0
danger_altitude: 3.5
Kv: 0.2

RelativeAltitudeReward_render: false
KH: 1.0

SmoothActionReward_render: false
